name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev alsa-utils

    - name: Configure CMake
      run: |
          cmake --version
          cmake -B build -DBUILD_SHARED_LIBS=FALSE

    - name: Build Project
      run: cmake --build build --config Release 

    - name: Run Executable
      run: pwd && echo && ls && echo && ls .. && echo && ./build/main
      working-directory: ${{ github.workspace }}
